### ISSUE TITLE
GDAL missing numpy dependency

### ISSUE THREAD

**Issue by m4tsa** [flathub/org.qgis.qgis#118]
When trying to load the [Virtual Raster Builder plugin](https://bitbucket.org/jakimowb/virtual-raster-builder) I get the following GDAL error:

```
Couldn't load plugin 'vrtbuilderplugin' due to an error when calling its initGui() method 

ModuleNotFoundError: No module named '_gdal_array' 
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/osgeo/gdal_array.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1014, in _gcd_import
  File "", line 991, in _find_and_load
  File "", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'osgeo._gdal_array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 360, in startPlugin
    plugins[packageName].initGui()
  File "/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/vrtbuilderplugin.py", line 48, in initGui
    from vrtbuilder.widgets import VRTBuilderWidget
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/widgets.py", line 28, in 
    from .externals.qps.maptools import SpatialExtentMapTool
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/externals/qps/maptools.py", line 54, in 
    from .utils import *
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder/externals/qps/utils.py", line 60, in 
    from osgeo import gdal, ogr, osr, gdal_array
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.8/site-packages/osgeo/gdal_array.py", line 17, in 
    _gdal_array = swig_import_helper()
  File "/app/lib/python3.8/site-packages/osgeo/gdal_array.py", line 16, in swig_import_helper
    return importlib.import_module('_gdal_array')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal_array'


Python version: 3.8.8 (default, Nov 10 2011, 15:00:00) [GCC 10.2.0] 
QGIS version: 3.20.2-Odense Odense, 9f59a156 

Python Path:
/app/share/qgis/python
/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/app/lib/python3.8/site-packages
/app/lib/python3.8/site-packages/numpy-1.19.5-py3.8-linux-x86_64.egg
/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/mats/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder
```

From what I can find this is caused by compiling GDAL without having numpy installed.

**Comment by Fenrihr** [comment]
same problem but with [CloudMasking](https://github.com/SMByC/CloudMasking) plugins

```
No se pudo cargar el complemento 'CloudMasking' debido a un error al llamar a su método classFactory() 

ModuleNotFoundError: No module named '_gdal_array' 
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/osgeo/gdal_array.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1014, in _gcd_import
  File "", line 991, in _find_and_load
  File "", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'osgeo._gdal_array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/__init__.py", line 128, in classFactory
    from .cloud_masking import CloudMasking
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/cloud_masking.py", line 39, in 
    from CloudMasking.core import cloud_filters, color_stack
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/core/cloud_filters.py", line 36, in 
    from CloudMasking.libs import gdal_merge, gdal_calc
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/libs/gdal_calc.py", line 54, in 
    from osgeo import gdalnumeric
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.8/site-packages/osgeo/gdalnumeric.py", line 2, in 
    from osgeo.gdal_array import *
  File "/app/share/qgis/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.8/site-packages/osgeo/gdal_array.py", line 17, in 
    _gdal_array = swig_import_helper()
  File "/app/lib/python3.8/site-packages/osgeo/gdal_array.py", line 16, in swig_import_helper
    return importlib.import_module('_gdal_array')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal_array'


Versión de Python: 3.8.8 (default, Nov 10 2011, 15:00:00) [GCC 10.2.0] 
Versión de QGIS: 3.20.3-Odense Odense, 495fbaec 

Ruta de Python:
/app/share/qgis/python
/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/app/lib/python3.8/site-packages
/app/lib/python3.8/site-packages/numpy-1.19.5-py3.8-linux-x86_64.egg
/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
/var/data/python/lib/python3.8/site-packages
/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/external/oauthlib-3.1.0-py2.py3-none-any.whl
/home/francisco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/external/requests_oauthlib-1.3.0-py2.py3-none-any.whl
```

**Comment by aleixpol** [comment]
As explained in the README, hope this helps: https://github.com/flathub/org.qgis.qgis/blob/master/README.md

**Comment by m4tsa** [comment]
> As explained in the README you will need to explicitly install the missing modules, hope this helps: https://github.com/flathub/org.qgis.qgis/blob/master/README.md

If you read the issue this is not a missing python module, but a included python module installed incorrectly.
