### ISSUE TITLE
geopunt plugin not working in flatpack qgis

### ISSUE THREAD

**Issue by reginaldc** [flathub/org.qgis.qgis#15]
Hi,

I got to install flatpack qgis on my laptop. No error installing qgis here.
When I wanted to install the geopunt4Qgis plugin I got an error.
I think it is due to missing python packages.
Is there a way to install a requirements.txt from within Qgis?

Regards,

Kon plug-in 'geopunt4Qgis' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

ImportError: No module named 'future' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/geopunt4Qgis/__init__.py", line 27, in classFactory
    from .geopunt4qgis import geopunt4Qgis
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/geopunt4Qgis/geopunt4qgis.py", line 33, in 
    from .geopunt4QgisGipod import geopunt4QgisGipodDialog
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/geopunt4Qgis/geopunt4QgisGipod.py", line 31, in 
    from .tools.gipod import gipodHelper, gipodWriter
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/geopunt4Qgis/tools/gipod.py", line 22, in 
    from future import standard_library
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named 'future'

Python versie: 3.5.2 (default, Sep 21 2018, 14:56:44) [GCC 6.4.0] 
QGIS versie: 3.2.3-Bonn Bonn, 9b17680 

Python pad:
/app/share/qgis/python
/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/app/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-x86_64.egg
/app/lib/python3.5/site-packages/MarkupSafe-1.0-py3.5-linux-x86_64.egg
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-linux
/usr/lib/python3.5/lib-dynload
/usr/lib/python3.5/site-packages
/usr/lib/python3.5/site-packages/setuptools-22.0.5-py3.5.egg
/app/lib/python3.5/site-packages
/home/reginald/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python

**Comment by aleixpol** [comment]
I'm not sure, I guess it's something to run by qgis upstream.

**Comment by aleixpol** [comment]
Do you think we should include the future python package?
Which others should we include?

**Comment by reginaldc** [comment]
It would be great to include all the python modules that are used by the most popular plugins

**Comment by neocals** [comment]
> It would be great to include all the python modules that are used by the most popular plugins

Same issue here with Plugin UMEP:  
ImportError: No module named 'future' 
Python version: 3.5.2 (default, Oct 11 2018, 08:33:18) [GCC 6.4.0] 
QGIS version: 3.4.4-Madeira Madeira, f6ddc62f

**Comment by matheusfillipe** [comment]
I still have the same issue... Seems like future wasn't included yet?
