### ISSUE TITLE
Error "ImportError: No module named 'future' "

### ISSUE THREAD

**Issue by marcogiannini** [flathub/org.qgis.qgis#16]
When i try to install _OSMDownloader_ or _qgis2web_ on KDE neon (bionic) i have this error both when I install and when I start qgis

No problem on Windows 10

```
Impossibile caricare il plugin 'OSMDownloader' a causa di un errore chiamando il metodo classFactory() 

ImportError: No module named 'future' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/marco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/__init__.py", line 34, in classFactory
    from .osmDownloader import OSMDownloader
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/osmDownloader.py", line 31, in 
    from .osmDownloader_dialog import OSMDownloaderDialog
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/osmDownloader_dialog.py", line 36, in 
    from .osm_downloader import OSMRequest
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/OSMDownloader/osm_downloader.py", line 25, in 
    from future import standard_library
  File "/app/share/qgis/python/qgis/utils.py", line 674, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named 'future'


Versione Python: 3.5.2 (default, Sep 21 2018, 14:56:44) [GCC 6.4.0] 
Versione di QGIS: 3.2.3-Bonn Bonn, 9b17680 

Percorso Python:
/app/share/qgis/python
/home/marco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/marco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/app/lib/python3.5/site-packages/numpy-1.11.2-py3.5-linux-x86_64.egg
/app/lib/python3.5/site-packages/MarkupSafe-1.0-py3.5-linux-x86_64.egg
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-linux
/usr/lib/python3.5/lib-dynload
/usr/lib/python3.5/site-packages
/usr/lib/python3.5/site-packages/setuptools-22.0.5-py3.5.egg
/app/lib/python3.5/site-packages
/home/marco/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
```

**Comment by aleixpol** [comment]
Let's centralise on #15.
