### ISSUE TITLE
QGIS 3.26: ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py) 

### ISSUE THREAD

**Issue by rduivenvoorde** [flathub/org.qgis.qgis#211]
On a fresh computer, running QGIS 3.26, QGIS is apparently missing a python module?

`
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py) 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/app/share/qgis/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/plugin.py", line 34, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 48, in 
    from MetaSearch.dialogs.manageconnectionsdialog import ManageConnectionsDialog
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/dialogs/manageconnectionsdialog.py", line 35, in 
    from MetaSearch.util import (get_connections_from_file, get_ui_class,
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/MetaSearch/util.py", line 38, in 
    from jinja2 import Environment, FileSystemLoader
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in 
    from .environment import Environment
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 25, in 
    from .defaults import BLOCK_END_STRING
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in 
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/lib/python3.9/site-packages/jinja2/filters.py", line 13, in 
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
`

![gnome-shell-screenshot-ghig25](https://user-images.githubusercontent.com/731673/179470644-9ecf4f5c-32f7-4ea6-aac3-dcfd6db1c870.png)

**Comment by agiudiceandrea** [comment]
> On a fresh computer

...with what OS?

Is issue is due to the fact that the MetaSearch plugin Python code uses the "jinja" Python library which in turn uses (in version 2.x) the `soft_unicode` function from the "markupsafe" Python library.
If in the Python environment used by QGIS is installed "jinja" version 2.x and "markupsafe" version > 2.0.1, then the error occurs because the `soft_unicode` function is not available in "markupsafe" version > 2.0.1.

The "markupsafe" Python library in the master branch of flathub/org.qgis.qgis is pinned to version 2.0.1 https://github.com/flathub/org.qgis.qgis/pull/175 https://github.com/flathub/org.qgis.qgis/blob/c574768a23fd1748276f06f2c9dd09b92adb01dd/org.qgis.qgis.json#L997 while it is not yet in branch/lts https://github.com/flathub/org.qgis.qgis/pull/204 https://github.com/flathub/org.qgis.qgis/blob/17d3583de2f51d2d97d45a6469bb78e94bcd8fc3/org.qgis.qgis.json#L989

Anyway it seems that in some systems the "markupsafe" Python library used by QGIS installed via the master branch of flathub/org.qgis.qgis is not the version 2.0.1, but at a newer version, even if it is explicitly pinned to version 2.0.1.
