### ISSUE TITLE
QGIS flatpak in Debian Buster

### ISSUE THREAD

**Issue by jllaube** [flathub/org.qgis.qgis#246]
After installing flatpak and then the latest version of QGIS and running QGIS, the menus don't open. I am using Gnome and Wayland.

Linux 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux

**Comment by aleixpol** [comment]
Can you confirm this is still an issue? It works for other users with similar set ups to yours.

**Comment by jllaube** [comment]
Hello,

I don't know because I uninstall this version of qgis and disable wayland.
A few minutes ago I tried to reinstall with flatpak and got this error:

Impossible de charger l'extension 'processing' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'numpy' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/app/share/qgis/python/plugins/processing/__init__.py", line 50, in classFactory
    from processing.ProcessingPlugin import ProcessingPlugin
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/ProcessingPlugin.py", line 49, in 
    from processing.gui.HistoryDialog import HistoryDialog
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/gui/HistoryDialog.py", line 40, in 
    from processing.gui import TestTools
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/gui/TestTools.py", line 34, in 
    from numpy import nan_to_num
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'numpy'


Version de Python : 3.10.6 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0] 
Version de QGIS : 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, exported 

Chemin Python :
/app/share/qgis/python
/home/jll/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/jll/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/app/lib/python3.10/site-packages
/usr/lib/python3.10/site-packages
/home/jll/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python

So I revert to QGIS 3.18.3-Zürich.

Best regards
