### ISSUE TITLE
ImportError: cannot import name 'QgsCodeEditorPython' from 'qgis.gui' 

### ISSUE THREAD

**Issue by olea** [flathub/org.qgis.qgis#79]
Hi:

I have several python errors related with some extensions but always related with this error message.

My installation:

```
QGIS Desktop - A Free and Open Source Geographic Information System

          ID: org.qgis.qgis
         Ref: app/org.qgis.qgis/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.16.0
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1.7?GB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: 2ff902bd1bd92b6cef5de23e3767d5388964aebfb58c0776bc721770f153798c
      Parent: 8782c25d8931afeded1fe6f0355c38545ea425ff0f4aaf730a8daec42b1eec16
     Subject: Python seems to prefer packages in /app/lib/python3.8 (aea8c50e)
        Date: 2020-11-09 01:42:59 +0000

``` 

The error details:

```

ImportError: cannot import name 'QgsCodeEditorPython' from 'qgis.gui' (/app/share/qgis/python/qgis/gui/__init__.py) 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/__init__.py", line 28, in classFactory
    from .qgis2web import Qgis2Web
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2web.py", line 29, in 
    from qgis2web.maindialog import MainDialog
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 63, in 
    from . import utils
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 50, in 
    import processing
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/__init__.py", line 26, in 
    from processing.tools.general import *  # NOQA
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/tools/general.py", line 32, in 
    from processing.core.Processing import Processing
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/core/Processing.py", line 77, in 
    from processing.modeler.ModelerAlgorithmProvider import ModelerAlgorithmProvider  # NOQA
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/modeler/ModelerAlgorithmProvider.py", line 40, in 
    from processing.modeler.CreateNewModelAction import CreateNewModelAction
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/modeler/CreateNewModelAction.py", line 32, in 
    from processing.modeler.ModelerDialog import ModelerDialog
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 56, in 
    from processing.script.ScriptEditorDialog import ScriptEditorDialog
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/script/ScriptEditorDialog.py", line 52, in 
    WIDGET, BASE = uic.loadUiType(
  File "/app/share/qgis/python/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/PyQt5/uic/__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 143, in 
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/script/ScriptEdit.py", line 28, in 
    from qgis.gui import QgsCodeEditorPython
ImportError: cannot import name 'QgsCodeEditorPython' from 'qgis.gui' (/app/share/qgis/python/qgis/gui/__init__.py)


Versión de Python: 3.8.6 (default, Nov 10 2011, 15:00:00) [GCC 10.2.0] 
Versión de QGIS: 3.16.0-Hannover Hannover, 43b64b13 

Ruta de Python:
/app/share/qgis/python
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/app/lib/python3.8/site-packages
/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg
/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/kmltools/libs
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/external/oauthlib-3.1.0-py2.py3-none-any.whl
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/external/requests_oauthlib-1.3.0-py2.py3-none-any.whl
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/excel_sync/libs/xlwt-1.3.0-py2.py3-none-any.whl
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/excel_sync/libs/xlrd-1.2.0-py2.py3-none-any.whl
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
/home/olea/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools
D:\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc
```

**Comment by olea** [comment]
There are more other errors related with the pyparsing, pygments and console modules.

FYI

**Comment by larsks** [comment]
I came here to file the same issue. I also ran into #80 while trying to resolve the error about `pygments`.

**Comment by aleixpol** [comment]
Yes, this one is driving me crazy, I don't really know why this is happening. I'll keep looking into it.

```
$ python3
Python 3.8.6 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.Qsci import QSCINTILLA_VERSION_STR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /app/lib/python3.8/site-packages/PyQt5/Qsci.so: undefined symbol: _ZTI8QsciAPIs
>>> 
```

**Comment by sk-dataocean-online** [comment]
I have the same issue with several plugins and console. Take a look here: https://github.com/qgis/QGIS/issues/39990

**Comment by olea** [comment]
Update:

```
          ID: org.qgis.qgis
  Referencia: app/org.qgis.qgis/x86_64/stable
Arquitectura: x86_64
        Rama: stable
     Version: 3.16.0
     License: GPL-2.0+
      Origen: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1,7 GB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: f1af8806e9f701768701fd6f25ba9ae84a3cc8e64e3303e03b441c5b0cf0478b
      Parent: e4148984e93351f9673e622d3148b04196dae2b26e84c065e75618fe05711551
     Subject: Force Qsci.so python plugin to link against libqscintilla-qt5.so (f85e11ff)
        Date: 2020-11-16 04:21:20 +0000

```

I needed to install the pyparsing module. After that the app seems to start fine, with this output:

```
Gtk-Message: 09:38:18.193: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:38:18.194: Failed to load module "pk-gtk-module"
Gtk-Message: 09:38:18.194: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:38:18.194: Failed to load module "pk-gtk-module"
Warning: Qt: Session management error: None of the authentication protocols specified are supported
Warning 1: libXML: 0: Element 'SrcSql': This element is not expected.
INFO:rdflib:RDFLib Version: 4.2.2
Warning: QMainWindow::saveState(): 'objectName' not set for QToolBar 0x557933deedd0 'SentinelHub'
```

just FYI.

Thanks!
